name: staging
description: Staging environment for pre-production testing
deployment_branch: main
protection_rules:
  - required_reviewers:
      users: [qa-lead, dev-lead]
  - required_approvals: 1
  - wait_timer: 5